apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-spring-boot-app
  template:
    metadata:
      labels:
        app: demo-spring-boot-app
    spec:
      containers:
      - name: demo-spring-boot-app
        image: nishantmpathak/demo-spring-boot-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: MY_CUSTOM_PROPERTY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: my.custom.property